### ISSUE TITLE
How to include raw files (e.g. CSS) in bundle size

### ISSUE THREAD

**Issue by dpschen** [okikio/bundle#10]
How can I include files like CSS in the final bundle size?

E.g. I wanted to compare the Vue 3 Version of v-tooltip with the vue2 version and for that wanted to include the CSS:

https://bundle.js.org/?bundle&share=KYDwDg9gTgLgBAbzgNQCoQgGxgSzHAXzgDMoIBbOAIgAsYYwBnALgHpWBXAOzAGsBzAHQBjCqwBuAWhgZseAAIAWQQAZVkgEbAYAQ0EAmVgBMcjGBOmzcYQeRxdBAK0ZUA3ACh3OcpFhwA5HQMLOzcfEKi5BYyWNZKqupaugbGpuZSMXI2woyM-kA

**Comment by okikio** [comment]
Sorry for the late response. This might be a little difficult, because CSS is treated differently than js, but I'll run a couple experiments and get back to you

**Comment by okikio** [comment]
This should now be fixed. Also, this url gives you more accurate results https://okikio-jantimon-bundle-6rp5grrp2r6gg-3000.githubpreview.dev/?share=KYDwDg9gTgLgBAbzgNQCoQgGxgSzHAXzgDMoIBbOAIgDcBaGDbPAAQBYA6ABm7oCNgMAIYcATFQDcAKCk5ykWHADkACxgwwAZwBcAel0BXAHZgA1gHMOAYwq76jLLjDtuvAcLG6AJjk0w7DExO1pqaSkA

**Comment by dpschen** [comment]
> Sorry for the late response.

No worries that was super fast =)
That solves the issue for me. Thank you so much 🥳
