### ISSUE TITLE
App appears broken and will not finish loading

### ISSUE THREAD

**Issue by markerikson** [okikio/bundle#12]
Hiya. Tried to use the site a couple weeks ago, but it appeared to break after a suggested page refresh. Came back to it today, and I'm seeing the same behavior. I tried clearing all workers/cookies/cache, etc, but I'm just seeing infinite spinners:

![image](https://user-images.githubusercontent.com/1128784/146118643-df828a45-1c61-4fdd-bff6-22b65bab4c39.png)

I'm getting these errors in the console:

```
// Error #1
SyntaxError: export declarations may only appear at top level of a module esbuild.worker.mjs:841:2489

// Error #2
Uncaught (in promise) Error: Illegal value for token color: #fff
    getId tokenization.js:113
    GF tokenization.js:91
    createFromParsedTokenTheme tokenization.js:139
    createFromRawTokenTheme tokenization.js:136
    get tokenTheme standaloneThemeServiceImpl.js:128
    _updateThemeOrColorMap standaloneThemeServiceImpl.js:288
    _updateActualTheme standaloneThemeServiceImpl.js:270
    setTheme standaloneThemeServiceImpl.js:259
    V_ standaloneCodeEditor.js:171
    x3 standaloneEditor.js:62
    KA standaloneEditor.js:49
    x3 standaloneEditor.js:61
    vZ monaco.ts:431
    Kn index.ts:324
    Kn index.ts:431
    i main.ts:99
    async* main.ts:103
    h api.es.js:2
    emit api.es.js:2
    forEach api.es.js:1
    emit api.es.js:2
    emit api.es.js:2
    method main.ts:114
    route api.es.js:2
    forEach api.es.js:1
    route api.es.js:2
    emit api.es.js:2
    forEach api.es.js:1
    emit api.es.js:2
    emit api.es.js:2
    _ready api.es.js:2
    boot api.es.js:2
    <anonymous> main.ts:118
    Kn index.ts:426
    AsyncFunctionNext self-hosted:674
    (Async: async)
    Kn index.ts:431
    i main.ts:99
    AsyncFunctionNext self-hosted:674
    (Async: async)
    <anonymous> main.ts:103
    h api.es.js:2
    emit api.es.js:2
    forEach self-hosted:1934
    forEach api.es.js:1
    emit api.es.js:2
    forEach self-hosted:206
    emit api.es.js:2
    method main.ts:114
    route api.es.js:2
    forEach self-hosted:1934
    forEach api.es.js:1
    route api.es.js:2
    emit api.es.js:2
    forEach self-hosted:1934
    forEach api.es.js:1
    emit api.es.js:2
    forEach self-hosted:206
    emit api.es.js:2
    _ready api.es.js:2
    _ready self-hosted:1161
    (Async: EventListener.handleEvent)
    boot api.es.js:2
    <anonymous> main.ts:118
    InnerModuleEvaluation self-hosted:2346
    evaluation self-hosted:2317
```

I'm using FF 84 on Windows, but I see the same behavior in latest Chrome as well.

Really love the tool - hopefully you can get it working again!

**Comment by okikio** [comment]
Yeah, sorry about that, the first error is from a change I made I've just sent out a fix for it, the second error seems to be from Monaco, I've also sent a fix for this issue, please tell me if that fixes the issue from your end.

> _**Note:**_ you may need to clear the cache for the site, browser sometimes hangs on to old cached items even if the a new update has been sent out.

**Comment by markerikson** [comment]
Sweet, working again! Thank you very much again both for the site and the fast response :)  

![image](https://user-images.githubusercontent.com/1128784/146122493-b053b881-6228-406b-ae7d-9248720ed706.png)

**Comment by okikio** [comment]
Thanks. It's awesome to see people using and benefiting from my project, I appreciate it.

**Comment by markerikson** [comment]
You're welcome! Totally understand that "hey, I made this thing, and people actually use it and like it!" feeling.

Obviously Bundlephobia is the main comparison/competitor here. They have some different feature sets - Bundlephobia does show that nice graph comparing different versions of the package over time.  But, it can't show nested entry points, and I love that Bundle shows the _real_ code output. Really lets you inspect it and see what you're getting in the output.

Not sure how much you've tried to actively promote the tool yet, but it's great and worth letting people know this exists :)

**Comment by okikio** [comment]
To be honest, I'm not sure how else to promote the tool, the only thing I've really done is to post about it on producthunt, https://www.producthunt.com/posts/bundle-6

**Comment by markerikson** [comment]
Heh, yeah, good question :)

At a minimum you could submit it to Reddit's https://www.reddit.com/r/javascript/ and maybe a couple other subs, as well as HN.  Might make a decent "Show HN" submission, really.

Heh, for that matter I'll go ahead and tweet a mention while I'm at it :)

**Comment by okikio** [comment]
Thanks. Here is the HN post https://news.ycombinator.com/item?id=29562183. Do you know of any other subreddits, etc... I should submit `bundle` to.
