### ISSUE TITLE
Ignore peer dependencies

### ISSUE THREAD

**Issue by intrnl** [okikio/bundle#13]
There should be a way to make some imports externalized (in this case, peer dependencies). With how it is right now, it doesn't seem to be a good way to measure how well your library gets bundled.

**Comment by okikio** [comment]
Unfortunately, yeah, you are correct, I'll see if I can find a better way to do this, but for now what I'd suggest doing is using https://esm.sh. It has the ability to set dependencies https://esm.sh/#specify-external-dependencies, e.g. so, if you wanted to bundle `swr` with a different version of react, you can use `esm:swr?deps=react@16.14.0` -> https://bundle.js.org/?q=esm:swr?deps=react@16.14.0&bundle

[![Open Bundle](https://bundle.js.org/badge-light.svg)](https://bundle.js.org/?q=esm:swr?deps=react@16.14.0&bundle)

**Comment by okikio** [comment]
You can now make deps external via the esbuild config

**Comment by okikio** [comment]
@intrnl Aliases and external packages are now officially supported
