### ISSUE TITLE
Add the size of source code

### ISSUE THREAD

**Issue by artalar** [okikio/bundle#14]
It would be nice to see the size of source code in the editor, it usefull for cases when you prototype something and just want to see the impact fo the minifyer.

It is not a necessary feature, just to improve UX a little bit.

**Comment by okikio** [comment]
As in the non bundled source codes file size

**Comment by okikio** [comment]
I'm not sure if this is what you meant but I've added a src code size display, 
![image](https://user-images.githubusercontent.com/17222836/150618451-60b87c6c-06c7-4ded-8a79-10b68adf756e.png)

**Comment by artalar** [comment]
Nice! Thank you!
