### ISSUE TITLE
Allow to specify a library version

### ISSUE THREAD

**Issue by artalar** [okikio/bundle#15]
It would be nice to have a possibility to specify version of libraries, like so `export * from 'lib@1.0.0'`

**Comment by okikio** [comment]
You can actually already do that

**Comment by artalar** [comment]
Sorry, but it isn't work for me

https://bundle.js.org/?q=@okikio/animate
<img width="1037" alt="CleanShot 2022-02-05 at 13 04 13@2x" src="https://user-images.githubusercontent.com/27290320/152637253-3c348865-06ee-43d7-bcb5-79676be775d0.png">

https://bundle.js.org/?q=@okikio/animate@2.3.1
<img width="1092" alt="CleanShot 2022-02-05 at 13 04 30@2x" src="https://user-images.githubusercontent.com/27290320/152637259-e90777f9-057a-4e2e-a881-3888ce9afa4d.png">

**Comment by okikio** [comment]
It seems there is a bug with the bundling process that causes esbuild to treeshake way too much, I'll have to investigate further and then get back to you

**Comment by okikio** [comment]
This bug is now fixed, and should be coming out in an update either today or tomorrow, most likely tomorrow

**Comment by okikio** [comment]
The bug has now officially been fixed, please tell me if you find any other bugs
