### ISSUE TITLE
Rename "btn-share"

### ISSUE THREAD

**Issue by SheetJSDev** [okikio/bundle#18]
First off, awesome work!

It's typical for ad blockers to block elements with class `btn-share` (and therefore hide the "Share" button) as it is typically used for social media links.

Please consider renaming the class to `btn-permalink` or something that is not typically blocked.

**Comment by okikio** [comment]
I've renamed the `btn-share` class, tell me what you think.

**Comment by SheetJSDev** [comment]
Awesome!  Now the button shows up
