### ISSUE TITLE
Error in `Bundled Code` if module has `node:` Imports

### ISSUE THREAD

**Issue by Semigradsky** [okikio/bundle#2]
https://nodejs.org/dist/latest-v16.x/docs/api/esm.html#esm_node_imports

Code:
```js
export * from "has-yarn"
```
Result:
```
> 107 B => 
> ...
>> Input Code: 
>> export * from "has-yarn"
>> Bundled Code: 
>> throw new Error('[Package Error] "node:process" does not exist. (Imported by "has-yarn.js").');
```

**Comment by okikio** [comment]
That error comes from https://skypack.dev CDN, unfortunately, the only way to load that specific package is to use https://unpkg.com, `export * from "unpkg:has-yarn"`

**Comment by okikio** [comment]
@Semigradsky Someone has already created an issue for this on https://github.com/skypackjs/skypack-cdn/issues/180, for now the only thing you can do is to use a different CDN.
