### ISSUE TITLE
Why does bundle have error squiggles?

### ISSUE THREAD

**Issue by styfle** [okikio/bundle#21]
Why does bundle show error squiggles for "Input", "Output" and "Console"?

Does this represent errors like in VS Code, or does it mean something else?

![image](https://user-images.githubusercontent.com/229881/165579312-c9fd5056-597a-4601-8b95-45f49d294ad0.png)

**Comment by okikio** [comment]
It's a stylistic design choice. I use it as an alternative to an underline. It really only counts as an error indicator is the squiggly lines are red.

**Comment by styfle** [comment]
I see. Why are those underlined?

**Comment by okikio** [comment]
1. It looked cool.
2. It helps indicate that you can click on the input and output buttons. Without the squiggly lines, the input and output buttons look like just random text that don't do anything.

**Comment by g-plane** [comment]
For me, it's confusing.

**Comment by okikio** [comment]
Well I'm always looking for ways to improve clarity and reduce confusion, do you have any ideas as to how I could avoid it being confusing, e.g. should I remove the underline?

**Comment by g-plane** [comment]
Personally, underlines are OK, but I think they shouldn't be squiggles.

**Comment by okikio** [comment]
@styfle Do you feel the same?

**Comment by styfle** [comment]
Yes, I was confused too. Underlines would be better 👍

**Comment by okikio** [comment]
Ok, I'll change it

**Comment by okikio** [comment]
This should now be fixed, please tell me what you think.

**Comment by g-plane** [comment]
That looks good. :+1:

**Comment by okikio** [comment]
@g-plane Awesome. @styfle You're the one who created this issue, am I good to close it?

**Comment by styfle** [comment]
Looks much better, thanks!
