### ISSUE TITLE
does not always work in Safari

### ISSUE THREAD

**Issue by Haroenv** [okikio/bundle#4]
I assume something about the bundling fails which causes `fs` to be undefined.

<img width="1440" alt="Screenshot 2021-09-13 at 10 54 42" src="https://user-images.githubusercontent.com/6270048/133054676-9239d451-b13d-4afc-b2ad-14cb3b6ec637.png">

I couldn't find a pattern to what makes this fail, it worked for the example, as well as `instantsearch.js` on the home page, but when I refreshed, the `instantsearch.js` didn't work

**Comment by okikio** [comment]
Unfortunately, I don't own a Mac so, I can't test on Safari, however, I'd like to know more about this issue, could you please describe what happens, before this error appears on Safari.

**Comment by Haroenv** [comment]
I'm not really sure how to describe the issue, but I can show the recording:

https://user-images.githubusercontent.com/6270048/133102781-cea694da-ae38-455c-88e9-08fa6fbad41f.mov



The fourth time I tried and refreshed it actually did work:

<img width="819" alt="Screenshot 2021-09-13 at 16 32 11" src="https://user-images.githubusercontent.com/6270048/133102764-dac8dd6d-8ada-4016-bf59-ba18f86c3b71.png">


I tried opening the devtools to the line of that error, but I guess the file is too big as it crashed my browser every time I tried to open it.

**Comment by okikio** [comment]
Yeah, don't try to inspect the code with devtools, it's about a MB (GZIPPED) in total of just pure code, it will crash basically every browsers devtools. 

Also, I heard Safari is very iffy in terms of reliability, so, sometimes it works, sometimes it doesn't. When I built https://bundle.js.org, I built using the lowest common denominator, making sure all the API's I used were also compatible with Safari, so, I'm not sure why Safari would be having such issues. Could please monitor this issue, to see if it occurs again? I'll close this issue for now, but if you are able to replicate the initial issue, I'll reopen it.

**Comment by Haroenv** [comment]
The video is a reproduction @okikio, I can reproduce it ~4/5 times

**Comment by okikio** [comment]
> The video is a reproduction @okikio, I can reproduce it ~4/5 times 

That's so odd, why does it do that?

**Comment by Haroenv** [comment]
I actually used the preview version of Safari, the latest stable version has a "unexpected keyword export", which I guess it because of modules not being supported in workers or something similar.

As it works as expected in other browsers, this just seems too bad, but no way to figure out what could cause it

**Comment by okikio** [comment]
> I actually used the preview version of Safari, the latest stable version has a "unexpected keyword export", which I guess it because of modules not being supported in workers or something similar.
> 
> As it works as expected in other browsers, this just seems too bad, but no way to figure out what could cause it

This might be an issue with Safari preview then. The "unexpected keyword export", is because using modules in workers just got added this year in Chrome, Firefox, and Safari, and since Safari only gets one update a year, the current stable Safari won't be getting support for modules in workers by maybe next month, when the Safari preview is moved to stable.

**Comment by okikio** [comment]
I'm reopening this issue, it seems @natemoo-re already solved a similar issue, in the Astro build repl.

**Comment by natemoo-re** [comment]
Not positive that #5 fixes the original issue, but it does seem to fix the "unexpected keyword export" issue in Firefox!

**Comment by okikio** [comment]
> Not positive that #5 fixes the original issue, but it does seem to fix the "unexpected keyword export" issue in Firefox!
> 
> **Edit** I'm having trouble reproducing the original issue on Safari v14. Not sure why!

@Haroenv Specified that on Safari it wouldn't work 4/5 tries, so, it may just be Safari being iffy

**Comment by okikio** [comment]
@Haroenv I've now merged your pull request @natemoo-re
